config/routes.rb
Photogur::Application.routes.draw do 
  resources :pictures

  root :to => "pictures#index" 

end

app/models/picture.rb
class Picture < ActiveRecord::Base
	scope :newest_first, -> { order("created_at DESC") }
	scope :most_recent_five, -> { newest_first.limit(5) }
	scope :created_before, ->(time) { where("created_at < ?", time) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
	
	def index
		@most_recent_pictures = Picture.most_recent_five
		@total = Picture.created_before(1.month.ago).count
		@one_month_ago = Picture.created_before(1.month.ago)
	end

	def show
		@picture = Picture.find(params[:id])
	end

	def new
		@picture = Picture.new
	end

	def edit
		@picture = Picture.find(params[:id])
	end

	def update
		@picture = Picture.find(params[:id])

		if @picture.update_attributes(picture_params)
			redirect_to "/pictures/#{@picture.id}"
		else 
			render :edit
		end
	end

	def create
		@picture = Picture.new(picture_params)
		if @picture.save
			redirect_to pictures_url
		else
			render :new
		end
		# render :text => "Saving a picture. URL: #{params[:url]}, Title: #{params[:title]}, Artist: #{params[:artist]}"
	end

	def destroy
		@picture = Picture.find(params[:id])
		@picture.destroy
		redirect_to pictures_url
	end
	
	private
	def picture_params
		params.require(:picture).permit(:artist, :title, :url)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Photogur</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pictures/edit.html.erb
<h1>Edit Picture</h1>

<p>
	<%= link_to "Back", @picture %>
</p>

<%= form_for @picture do |f| %>
	<p>
		<%= f.label "artist" %><br>
		<%= f.text_field "artist" %>
	</p>
	<p>
		<%= f.label "title" %><br>
		<%= f.text_field "title" %>
	</p>
	<p>
		<%= f.label "url" %><br>
		<%= f.text_field "url" %>
	</p>
	<p>
		<%= submit_tag "Save" %>
	</p>
<% end %>

app/views/pictures/index.html.erb
<h1>Most recent pictures</h1>
<ul>
	<% @most_recent_pictures.each do |picture| %>
		<li><%= picture.title %></li>
	<% end %>
</ul>

<ul>
	<% @one_month_ago.each do |picture| %>
		<li><%= picture.title %></li>
	<% end %>
</ul>


<%= @total %>

app/views/pictures/new.html.erb
<h1>Add a picture</h1>
<%= link_to "Back to Pictures", pictures_url %>
<%= form_for @picture do |f| %>
  <p>
    <%= f.label "artist" %><br>
    <%= f.text_field "artist" %>
  </p>
  <p>
    <%= f.label "title" %><br>
    <%= f.text_field "title" %>
  </p>
  <p>
    <%= f.label "url" %><br>
    <%= f.text_field "url" %>
  </p>
  <p>
    <%= submit_tag "Save" %>
  </p>
<% end %>

app/views/pictures/picture0.html.erb
<p><%= @picture[:title] %>, <%= @picture[:artist] %></p>
<img src="<%= @picture[:url] %>">

app/views/pictures/show.html.erb
<%= link_to "Back to Pictures", pictures_url %> | <%= link_to "Edit", edit_picture_path(@picture) %> | 
<%= link_to "Delete", @picture, :confirm => "Are you sure you want to delete this picture?", :method => 
:delete %> 

<p><%= @picture[:title] %>, <%= @picture[:artist] %></p>
<%= image_tag @picture.url %>